/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.SummaryAthlete

/**
 * 
 * @param id The unique identifier of this comment
 * @param activityId The identifier of the activity this comment is related to
 * @param text The content of the comment
 * @param athlete 
 * @param createdAt The time at which this comment was created.
 */
data class Comment (

    /* The unique identifier of this comment */
    val id: kotlin.Long? = null,
    /* The identifier of the activity this comment is related to */
    val activityId: kotlin.Long? = null,
    /* The content of the comment */
    val text: kotlin.String? = null,
    val athlete: SummaryAthlete? = null,
    /* The time at which this comment was created. */
    val createdAt: java.time.LocalDateTime? = null
) {
}