/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.MetaActivity
import io.swagger.client.models.MetaAthlete
import io.swagger.client.models.SummarySegment
import io.swagger.client.models.SummarySegmentEffort

/**
 * 
 * @param name The name of the segment on which this effort was performed
 * @param activity 
 * @param athlete 
 * @param movingTime The effort's moving time
 * @param startIndex The start index of this effort in its activity's stream
 * @param endIndex The end index of this effort in its activity's stream
 * @param averageCadence The effort's average cadence
 * @param averageWatts The average wattage of this effort
 * @param deviceWatts For riding efforts, whether the wattage was reported by a dedicated recording device
 * @param averageHeartrate The heart heart rate of the athlete during this effort
 * @param maxHeartrate The maximum heart rate of the athlete during this effort
 * @param segment 
 * @param komRank The rank of the effort on the global leaderboard if it belongs in the top 10 at the time of upload
 * @param prRank The rank of the effort on the athlete's leaderboard if it belongs in the top 3 at the time of upload
 * @param hidden Whether this effort should be hidden when viewed within an activity
 */
data class DetailedSegmentEffort (

    /* The name of the segment on which this effort was performed */
    val name: kotlin.String? = null,
    val activity: MetaActivity? = null,
    val athlete: MetaAthlete? = null,
    /* The effort's moving time */
    val movingTime: kotlin.Int? = null,
    /* The start index of this effort in its activity's stream */
    val startIndex: kotlin.Int? = null,
    /* The end index of this effort in its activity's stream */
    val endIndex: kotlin.Int? = null,
    /* The effort's average cadence */
    val averageCadence: kotlin.Float? = null,
    /* The average wattage of this effort */
    val averageWatts: kotlin.Float? = null,
    /* For riding efforts, whether the wattage was reported by a dedicated recording device */
    val deviceWatts: kotlin.Boolean? = null,
    /* The heart heart rate of the athlete during this effort */
    val averageHeartrate: kotlin.Float? = null,
    /* The maximum heart rate of the athlete during this effort */
    val maxHeartrate: kotlin.Float? = null,
    val segment: SummarySegment? = null,
    /* The rank of the effort on the global leaderboard if it belongs in the top 10 at the time of upload */
    val komRank: kotlin.Int? = null,
    /* The rank of the effort on the athlete's leaderboard if it belongs in the top 3 at the time of upload */
    val prRank: kotlin.Int? = null,
    /* Whether this effort should be hidden when viewed within an activity */
    val hidden: kotlin.Boolean? = null,
    /* The unique identifier of this effort */
    val id: kotlin.Long? = null,
    /* The effort's elapsed time */
    val elapsedTime: kotlin.Int? = null,
    /* The time at which the effort was started. */
    val startDate: java.time.LocalDateTime? = null,
    /* The time at which the effort was started in the local timezone. */
    val startDateLocal: java.time.LocalDateTime? = null,
    /* The effort's distance in meters */
    val distance: kotlin.Float? = null,
    /* Whether this effort is the current best on the leaderboard */
    val isKom: kotlin.Boolean? = null,
    /* The name of the segment on which this effort was performed */
    val name: kotlin.String? = null,
    val activity: MetaActivity? = null,
    val athlete: MetaAthlete? = null,
    /* The effort's moving time */
    val movingTime: kotlin.Int? = null,
    /* The start index of this effort in its activity's stream */
    val startIndex: kotlin.Int? = null,
    /* The end index of this effort in its activity's stream */
    val endIndex: kotlin.Int? = null,
    /* The effort's average cadence */
    val averageCadence: kotlin.Float? = null,
    /* The average wattage of this effort */
    val averageWatts: kotlin.Float? = null,
    /* For riding efforts, whether the wattage was reported by a dedicated recording device */
    val deviceWatts: kotlin.Boolean? = null,
    /* The heart heart rate of the athlete during this effort */
    val averageHeartrate: kotlin.Float? = null,
    /* The maximum heart rate of the athlete during this effort */
    val maxHeartrate: kotlin.Float? = null,
    val segment: SummarySegment? = null,
    /* The rank of the effort on the global leaderboard if it belongs in the top 10 at the time of upload */
    val komRank: kotlin.Int? = null,
    /* The rank of the effort on the athlete's leaderboard if it belongs in the top 3 at the time of upload */
    val prRank: kotlin.Int? = null,
    /* Whether this effort should be hidden when viewed within an activity */
    val hidden: kotlin.Boolean? = null
) {
}