/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ActivityType
import io.swagger.client.models.DetailedSegmentEffort
import io.swagger.client.models.Lap
import io.swagger.client.models.LatLng
import io.swagger.client.models.MetaAthlete
import io.swagger.client.models.PhotosSummary
import io.swagger.client.models.PolylineMap
import io.swagger.client.models.Split
import io.swagger.client.models.SummaryActivity
import io.swagger.client.models.SummaryGear

/**
 * 
 * @param description The description of the activity
 * @param photos 
 * @param gear 
 * @param calories The number of kilocalories consumed during this activity
 * @param segmentEfforts 
 * @param deviceName The name of the device used to record the activity
 * @param embedToken The token used to embed a Strava activity
 * @param splitsMetric The splits of this activity in metric units (for runs)
 * @param splitsStandard The splits of this activity in imperial units (for runs)
 * @param laps 
 * @param bestEfforts 
 */
data class DetailedActivity (

    /* The description of the activity */
    val description: kotlin.String? = null,
    val photos: PhotosSummary? = null,
    val gear: SummaryGear? = null,
    /* The number of kilocalories consumed during this activity */
    val calories: kotlin.Float? = null,
    val segmentEfforts: kotlin.Array<DetailedSegmentEffort>? = null,
    /* The name of the device used to record the activity */
    val deviceName: kotlin.String? = null,
    /* The token used to embed a Strava activity */
    val embedToken: kotlin.String? = null,
    /* The splits of this activity in metric units (for runs) */
    val splitsMetric: kotlin.Array<Split>? = null,
    /* The splits of this activity in imperial units (for runs) */
    val splitsStandard: kotlin.Array<Split>? = null,
    val laps: kotlin.Array<Lap>? = null,
    val bestEfforts: kotlin.Array<DetailedSegmentEffort>? = null,
    /* The identifier provided at upload time */
    val externalId: kotlin.String? = null,
    /* The identifier of the upload that resulted in this activity */
    val uploadId: kotlin.Long? = null,
    val athlete: MetaAthlete? = null,
    /* The name of the activity */
    val name: kotlin.String? = null,
    /* The activity's distance, in meters */
    val distance: kotlin.Float? = null,
    /* The activity's moving time, in seconds */
    val movingTime: kotlin.Int? = null,
    /* The activity's elapsed time, in seconds */
    val elapsedTime: kotlin.Int? = null,
    /* The activity's total elevation gain. */
    val totalElevationGain: kotlin.Float? = null,
    /* The activity's highest elevation, in meters */
    val elevHigh: kotlin.Float? = null,
    /* The activity's lowest elevation, in meters */
    val elevLow: kotlin.Float? = null,
    val type: ActivityType? = null,
    /* The time at which the activity was started. */
    val startDate: java.time.LocalDateTime? = null,
    /* The time at which the activity was started in the local timezone. */
    val startDateLocal: java.time.LocalDateTime? = null,
    /* The timezone of the activity */
    val timezone: kotlin.String? = null,
    val startLatlng: LatLng? = null,
    val endLatlng: LatLng? = null,
    /* The number of achievements gained during this activity */
    val achievementCount: kotlin.Int? = null,
    /* The number of kudos given for this activity */
    val kudosCount: kotlin.Int? = null,
    /* The number of comments for this activity */
    val commentCount: kotlin.Int? = null,
    /* The number of athletes for taking part in a group activity */
    val athleteCount: kotlin.Int? = null,
    /* The number of Instagram photos for this activity */
    val photoCount: kotlin.Int? = null,
    /* The number of Instagram and Strava photos for this activity */
    val totalPhotoCount: kotlin.Int? = null,
    val map: PolylineMap? = null,
    /* Whether this activity was recorded on a training machine */
    val trainer: kotlin.Boolean? = null,
    /* Whether this activity is a commute */
    val commute: kotlin.Boolean? = null,
    /* Whether this activity was created manually */
    val manual: kotlin.Boolean? = null,
    /* Whether this activity is private */
    val `private`: kotlin.Boolean? = null,
    /* Whether this activity is flagged */
    val flagged: kotlin.Boolean? = null,
    /* The activity's workout type */
    val workoutType: kotlin.Int? = null,
    /* The unique identifier of the upload in string format */
    val uploadIdStr: kotlin.String? = null,
    /* The activity's average speed, in meters per second */
    val averageSpeed: kotlin.Float? = null,
    /* The activity's max speed, in meters per second */
    val maxSpeed: kotlin.Float? = null,
    /* Whether the logged-in athlete has kudoed this activity */
    val hasKudoed: kotlin.Boolean? = null,
    /* The id of the gear for the activity */
    val gearId: kotlin.String? = null,
    /* The total work done in kilojoules during this activity. Rides only */
    val kilojoules: kotlin.Float? = null,
    /* Average power output in watts during this activity. Rides only */
    val averageWatts: kotlin.Float? = null,
    /* Whether the watts are from a power meter, false if estimated */
    val deviceWatts: kotlin.Boolean? = null,
    /* Rides with power meter data only */
    val maxWatts: kotlin.Int? = null,
    /* Similar to Normalized Power. Rides with power meter data only */
    val weightedAverageWatts: kotlin.Int? = null,
    /* The description of the activity */
    val description: kotlin.String? = null,
    val photos: PhotosSummary? = null,
    val gear: SummaryGear? = null,
    /* The number of kilocalories consumed during this activity */
    val calories: kotlin.Float? = null,
    val segmentEfforts: kotlin.Array<DetailedSegmentEffort>? = null,
    /* The name of the device used to record the activity */
    val deviceName: kotlin.String? = null,
    /* The token used to embed a Strava activity */
    val embedToken: kotlin.String? = null,
    /* The splits of this activity in metric units (for runs) */
    val splitsMetric: kotlin.Array<Split>? = null,
    /* The splits of this activity in imperial units (for runs) */
    val splitsStandard: kotlin.Array<Split>? = null,
    val laps: kotlin.Array<Lap>? = null,
    val bestEfforts: kotlin.Array<DetailedSegmentEffort>? = null
) {
}