/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ActivityType
import io.swagger.client.models.LatLng
import io.swagger.client.models.MetaActivity
import io.swagger.client.models.MetaAthlete
import io.swagger.client.models.PolylineMap

/**
 * 
 * @param externalId The identifier provided at upload time
 * @param uploadId The identifier of the upload that resulted in this activity
 * @param athlete 
 * @param name The name of the activity
 * @param distance The activity's distance, in meters
 * @param movingTime The activity's moving time, in seconds
 * @param elapsedTime The activity's elapsed time, in seconds
 * @param totalElevationGain The activity's total elevation gain.
 * @param elevHigh The activity's highest elevation, in meters
 * @param elevLow The activity's lowest elevation, in meters
 * @param type 
 * @param startDate The time at which the activity was started.
 * @param startDateLocal The time at which the activity was started in the local timezone.
 * @param timezone The timezone of the activity
 * @param startLatlng 
 * @param endLatlng 
 * @param achievementCount The number of achievements gained during this activity
 * @param kudosCount The number of kudos given for this activity
 * @param commentCount The number of comments for this activity
 * @param athleteCount The number of athletes for taking part in a group activity
 * @param photoCount The number of Instagram photos for this activity
 * @param totalPhotoCount The number of Instagram and Strava photos for this activity
 * @param map 
 * @param trainer Whether this activity was recorded on a training machine
 * @param commute Whether this activity is a commute
 * @param manual Whether this activity was created manually
 * @param &#x60;private&#x60; Whether this activity is private
 * @param flagged Whether this activity is flagged
 * @param workoutType The activity's workout type
 * @param uploadIdStr The unique identifier of the upload in string format
 * @param averageSpeed The activity's average speed, in meters per second
 * @param maxSpeed The activity's max speed, in meters per second
 * @param hasKudoed Whether the logged-in athlete has kudoed this activity
 * @param gearId The id of the gear for the activity
 * @param kilojoules The total work done in kilojoules during this activity. Rides only
 * @param averageWatts Average power output in watts during this activity. Rides only
 * @param deviceWatts Whether the watts are from a power meter, false if estimated
 * @param maxWatts Rides with power meter data only
 * @param weightedAverageWatts Similar to Normalized Power. Rides with power meter data only
 */
data class SummaryActivity (

    /* The identifier provided at upload time */
    val externalId: kotlin.String? = null,
    /* The identifier of the upload that resulted in this activity */
    val uploadId: kotlin.Long? = null,
    val athlete: MetaAthlete? = null,
    /* The name of the activity */
    val name: kotlin.String? = null,
    /* The activity's distance, in meters */
    val distance: kotlin.Float? = null,
    /* The activity's moving time, in seconds */
    val movingTime: kotlin.Int? = null,
    /* The activity's elapsed time, in seconds */
    val elapsedTime: kotlin.Int? = null,
    /* The activity's total elevation gain. */
    val totalElevationGain: kotlin.Float? = null,
    /* The activity's highest elevation, in meters */
    val elevHigh: kotlin.Float? = null,
    /* The activity's lowest elevation, in meters */
    val elevLow: kotlin.Float? = null,
    val type: ActivityType? = null,
    /* The time at which the activity was started. */
    val startDate: java.time.LocalDateTime? = null,
    /* The time at which the activity was started in the local timezone. */
    val startDateLocal: java.time.LocalDateTime? = null,
    /* The timezone of the activity */
    val timezone: kotlin.String? = null,
    val startLatlng: LatLng? = null,
    val endLatlng: LatLng? = null,
    /* The number of achievements gained during this activity */
    val achievementCount: kotlin.Int? = null,
    /* The number of kudos given for this activity */
    val kudosCount: kotlin.Int? = null,
    /* The number of comments for this activity */
    val commentCount: kotlin.Int? = null,
    /* The number of athletes for taking part in a group activity */
    val athleteCount: kotlin.Int? = null,
    /* The number of Instagram photos for this activity */
    val photoCount: kotlin.Int? = null,
    /* The number of Instagram and Strava photos for this activity */
    val totalPhotoCount: kotlin.Int? = null,
    val map: PolylineMap? = null,
    /* Whether this activity was recorded on a training machine */
    val trainer: kotlin.Boolean? = null,
    /* Whether this activity is a commute */
    val commute: kotlin.Boolean? = null,
    /* Whether this activity was created manually */
    val manual: kotlin.Boolean? = null,
    /* Whether this activity is private */
    val `private`: kotlin.Boolean? = null,
    /* Whether this activity is flagged */
    val flagged: kotlin.Boolean? = null,
    /* The activity's workout type */
    val workoutType: kotlin.Int? = null,
    /* The unique identifier of the upload in string format */
    val uploadIdStr: kotlin.String? = null,
    /* The activity's average speed, in meters per second */
    val averageSpeed: kotlin.Float? = null,
    /* The activity's max speed, in meters per second */
    val maxSpeed: kotlin.Float? = null,
    /* Whether the logged-in athlete has kudoed this activity */
    val hasKudoed: kotlin.Boolean? = null,
    /* The id of the gear for the activity */
    val gearId: kotlin.String? = null,
    /* The total work done in kilojoules during this activity. Rides only */
    val kilojoules: kotlin.Float? = null,
    /* Average power output in watts during this activity. Rides only */
    val averageWatts: kotlin.Float? = null,
    /* Whether the watts are from a power meter, false if estimated */
    val deviceWatts: kotlin.Boolean? = null,
    /* Rides with power meter data only */
    val maxWatts: kotlin.Int? = null,
    /* Similar to Normalized Power. Rides with power meter data only */
    val weightedAverageWatts: kotlin.Int? = null,
    /* The unique identifier of the activity */
    val id: kotlin.Long? = null,
    /* The identifier provided at upload time */
    val externalId: kotlin.String? = null,
    /* The identifier of the upload that resulted in this activity */
    val uploadId: kotlin.Long? = null,
    val athlete: MetaAthlete? = null,
    /* The name of the activity */
    val name: kotlin.String? = null,
    /* The activity's distance, in meters */
    val distance: kotlin.Float? = null,
    /* The activity's moving time, in seconds */
    val movingTime: kotlin.Int? = null,
    /* The activity's elapsed time, in seconds */
    val elapsedTime: kotlin.Int? = null,
    /* The activity's total elevation gain. */
    val totalElevationGain: kotlin.Float? = null,
    /* The activity's highest elevation, in meters */
    val elevHigh: kotlin.Float? = null,
    /* The activity's lowest elevation, in meters */
    val elevLow: kotlin.Float? = null,
    val type: ActivityType? = null,
    /* The time at which the activity was started. */
    val startDate: java.time.LocalDateTime? = null,
    /* The time at which the activity was started in the local timezone. */
    val startDateLocal: java.time.LocalDateTime? = null,
    /* The timezone of the activity */
    val timezone: kotlin.String? = null,
    val startLatlng: LatLng? = null,
    val endLatlng: LatLng? = null,
    /* The number of achievements gained during this activity */
    val achievementCount: kotlin.Int? = null,
    /* The number of kudos given for this activity */
    val kudosCount: kotlin.Int? = null,
    /* The number of comments for this activity */
    val commentCount: kotlin.Int? = null,
    /* The number of athletes for taking part in a group activity */
    val athleteCount: kotlin.Int? = null,
    /* The number of Instagram photos for this activity */
    val photoCount: kotlin.Int? = null,
    /* The number of Instagram and Strava photos for this activity */
    val totalPhotoCount: kotlin.Int? = null,
    val map: PolylineMap? = null,
    /* Whether this activity was recorded on a training machine */
    val trainer: kotlin.Boolean? = null,
    /* Whether this activity is a commute */
    val commute: kotlin.Boolean? = null,
    /* Whether this activity was created manually */
    val manual: kotlin.Boolean? = null,
    /* Whether this activity is private */
    val `private`: kotlin.Boolean? = null,
    /* Whether this activity is flagged */
    val flagged: kotlin.Boolean? = null,
    /* The activity's workout type */
    val workoutType: kotlin.Int? = null,
    /* The unique identifier of the upload in string format */
    val uploadIdStr: kotlin.String? = null,
    /* The activity's average speed, in meters per second */
    val averageSpeed: kotlin.Float? = null,
    /* The activity's max speed, in meters per second */
    val maxSpeed: kotlin.Float? = null,
    /* Whether the logged-in athlete has kudoed this activity */
    val hasKudoed: kotlin.Boolean? = null,
    /* The id of the gear for the activity */
    val gearId: kotlin.String? = null,
    /* The total work done in kilojoules during this activity. Rides only */
    val kilojoules: kotlin.Float? = null,
    /* Average power output in watts during this activity. Rides only */
    val averageWatts: kotlin.Float? = null,
    /* Whether the watts are from a power meter, false if estimated */
    val deviceWatts: kotlin.Boolean? = null,
    /* Rides with power meter data only */
    val maxWatts: kotlin.Int? = null,
    /* Similar to Normalized Power. Rides with power meter data only */
    val weightedAverageWatts: kotlin.Int? = null
) {
}