/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ZoneRange

/**
 * A union type representing the time spent in a given zone.
 * @param time The number of seconds spent in this zone
 */
data class TimedZoneRange (

    /* The number of seconds spent in this zone */
    val time: kotlin.Int? = null,
    /* The minimum value in the range. */
    val min: kotlin.Int? = null,
    /* The maximum value in the range. */
    val max: kotlin.Int? = null,
    /* The number of seconds spent in this zone */
    val time: kotlin.Int? = null
) {
}