/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* The version of the OpenAPI document: 3.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.SummaryAthlete

import com.squareup.moshi.Json
/**
 * 
 * @param id The unique identifier of this comment
 * @param activityId The identifier of the activity this comment is related to
 * @param text The content of the comment
 * @param athlete 
 * @param createdAt The time at which this comment was created.
 */

data class Comment (
    /* The unique identifier of this comment */
    @Json(name = "id")
    val id: kotlin.Long? = null,
    /* The identifier of the activity this comment is related to */
    @Json(name = "activity_id")
    val activityId: kotlin.Long? = null,
    /* The content of the comment */
    @Json(name = "text")
    val text: kotlin.String? = null,
    @Json(name = "athlete")
    val athlete: SummaryAthlete? = null,
    /* The time at which this comment was created. */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null
)

