/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* The version of the OpenAPI document: 3.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.DetailedSegmentEffort
import org.openapitools.client.models.Lap
import org.openapitools.client.models.PhotosSummary
import org.openapitools.client.models.Split
import org.openapitools.client.models.SummaryGear

import com.squareup.moshi.Json
/**
 * 
 * @param description The description of the activity
 * @param photos 
 * @param gear 
 * @param calories The number of kilocalories consumed during this activity
 * @param segmentEfforts 
 * @param deviceName The name of the device used to record the activity
 * @param embedToken The token used to embed a Strava activity
 * @param splitsMetric The splits of this activity in metric units (for runs)
 * @param splitsStandard The splits of this activity in imperial units (for runs)
 * @param laps 
 * @param bestEfforts 
 */

data class DetailedActivityAllOf (
    /* The description of the activity */
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "photos")
    val photos: PhotosSummary? = null,
    @Json(name = "gear")
    val gear: SummaryGear? = null,
    /* The number of kilocalories consumed during this activity */
    @Json(name = "calories")
    val calories: kotlin.Float? = null,
    @Json(name = "segment_efforts")
    val segmentEfforts: kotlin.Array<DetailedSegmentEffort>? = null,
    /* The name of the device used to record the activity */
    @Json(name = "device_name")
    val deviceName: kotlin.String? = null,
    /* The token used to embed a Strava activity */
    @Json(name = "embed_token")
    val embedToken: kotlin.String? = null,
    /* The splits of this activity in metric units (for runs) */
    @Json(name = "splits_metric")
    val splitsMetric: kotlin.Array<Split>? = null,
    /* The splits of this activity in imperial units (for runs) */
    @Json(name = "splits_standard")
    val splitsStandard: kotlin.Array<Split>? = null,
    @Json(name = "laps")
    val laps: kotlin.Array<Lap>? = null,
    @Json(name = "best_efforts")
    val bestEfforts: kotlin.Array<DetailedSegmentEffort>? = null
)

