/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* The version of the OpenAPI document: 3.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param code The code associated with this error.
 * @param field The specific field or aspect of the resource associated with this error.
 * @param resource The type of resource associated with this error.
 */

data class Error (
    /* The code associated with this error. */
    @Json(name = "code")
    val code: kotlin.String? = null,
    /* The specific field or aspect of the resource associated with this error. */
    @Json(name = "field")
    val field: kotlin.String? = null,
    /* The type of resource associated with this error. */
    @Json(name = "resource")
    val resource: kotlin.String? = null
)

