/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* The version of the OpenAPI document: 3.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param averageSpeed The average speed of this split, in meters per second
 * @param distance The distance of this split, in meters
 * @param elapsedTime The elapsed time of this split, in seconds
 * @param elevationDifference The elevation difference of this split, in meters
 * @param paceZone The pacing zone of this split
 * @param movingTime The moving time of this split, in seconds
 * @param split N/A
 */

data class Split (
    /* The average speed of this split, in meters per second */
    @Json(name = "average_speed")
    val averageSpeed: kotlin.Float? = null,
    /* The distance of this split, in meters */
    @Json(name = "distance")
    val distance: kotlin.Float? = null,
    /* The elapsed time of this split, in seconds */
    @Json(name = "elapsed_time")
    val elapsedTime: kotlin.Int? = null,
    /* The elevation difference of this split, in meters */
    @Json(name = "elevation_difference")
    val elevationDifference: kotlin.Float? = null,
    /* The pacing zone of this split */
    @Json(name = "pace_zone")
    val paceZone: kotlin.Int? = null,
    /* The moving time of this split, in seconds */
    @Json(name = "moving_time")
    val movingTime: kotlin.Int? = null,
    /* N/A */
    @Json(name = "split")
    val split: kotlin.Int? = null
)

