/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* The version of the OpenAPI document: 3.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AltitudeStream
import org.openapitools.client.models.CadenceStream
import org.openapitools.client.models.DistanceStream
import org.openapitools.client.models.HeartrateStream
import org.openapitools.client.models.LatLngStream
import org.openapitools.client.models.MovingStream
import org.openapitools.client.models.PowerStream
import org.openapitools.client.models.SmoothGradeStream
import org.openapitools.client.models.SmoothVelocityStream
import org.openapitools.client.models.TemperatureStream
import org.openapitools.client.models.TimeStream

import com.squareup.moshi.Json
/**
 * 
 * @param time 
 * @param distance 
 * @param latlng 
 * @param altitude 
 * @param velocitySmooth 
 * @param heartrate 
 * @param cadence 
 * @param watts 
 * @param temp 
 * @param moving 
 * @param gradeSmooth 
 */

data class StreamSet (
    @Json(name = "time")
    val time: TimeStream? = null,
    @Json(name = "distance")
    val distance: DistanceStream? = null,
    @Json(name = "latlng")
    val latlng: LatLngStream? = null,
    @Json(name = "altitude")
    val altitude: AltitudeStream? = null,
    @Json(name = "velocity_smooth")
    val velocitySmooth: SmoothVelocityStream? = null,
    @Json(name = "heartrate")
    val heartrate: HeartrateStream? = null,
    @Json(name = "cadence")
    val cadence: CadenceStream? = null,
    @Json(name = "watts")
    val watts: PowerStream? = null,
    @Json(name = "temp")
    val temp: TemperatureStream? = null,
    @Json(name = "moving")
    val moving: MovingStream? = null,
    @Json(name = "grade_smooth")
    val gradeSmooth: SmoothGradeStream? = null
)

