/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* The version of the OpenAPI document: 3.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param id The unique identifier of this effort
 * @param elapsedTime The effort's elapsed time
 * @param startDate The time at which the effort was started.
 * @param startDateLocal The time at which the effort was started in the local timezone.
 * @param distance The effort's distance in meters
 * @param isKom Whether this effort is the current best on the leaderboard
 */

data class SummarySegmentEffort (
    /* The unique identifier of this effort */
    @Json(name = "id")
    val id: kotlin.Long? = null,
    /* The effort's elapsed time */
    @Json(name = "elapsed_time")
    val elapsedTime: kotlin.Int? = null,
    /* The time at which the effort was started. */
    @Json(name = "start_date")
    val startDate: java.time.OffsetDateTime? = null,
    /* The time at which the effort was started in the local timezone. */
    @Json(name = "start_date_local")
    val startDateLocal: java.time.OffsetDateTime? = null,
    /* The effort's distance in meters */
    @Json(name = "distance")
    val distance: kotlin.Float? = null,
    /* Whether this effort is the current best on the leaderboard */
    @Json(name = "is_kom")
    val isKom: kotlin.Boolean? = null
)

