/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* The version of the OpenAPI document: 3.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.TimedZoneRangeAllOf
import org.openapitools.client.models.ZoneRange

import com.squareup.moshi.Json
/**
 * A union type representing the time spent in a given zone.
 * @param min The minimum value in the range.
 * @param max The maximum value in the range.
 * @param time The number of seconds spent in this zone
 */

data class TimedZoneRange (
    /* The minimum value in the range. */
    @Json(name = "min")
    val min: kotlin.Int? = null,
    /* The maximum value in the range. */
    @Json(name = "max")
    val max: kotlin.Int? = null,
    /* The number of seconds spent in this zone */
    @Json(name = "time")
    val time: kotlin.Int? = null
)

