/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* The version of the OpenAPI document: 3.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ActivityType

import com.squareup.moshi.Json
/**
 * 
 * @param commute Whether this activity is a commute
 * @param trainer Whether this activity was recorded on a training machine
 * @param description The description of the activity
 * @param name The name of the activity
 * @param type 
 * @param gearId Identifier for the gear associated with the activity. ‘none’ clears gear from activity
 */

data class UpdatableActivity (
    /* Whether this activity is a commute */
    @Json(name = "commute")
    val commute: kotlin.Boolean? = null,
    /* Whether this activity was recorded on a training machine */
    @Json(name = "trainer")
    val trainer: kotlin.Boolean? = null,
    /* The description of the activity */
    @Json(name = "description")
    val description: kotlin.String? = null,
    /* The name of the activity */
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "type")
    val type: ActivityType? = null,
    /* Identifier for the gear associated with the activity. ‘none’ clears gear from activity */
    @Json(name = "gear_id")
    val gearId: kotlin.String? = null
)

