/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* The version of the OpenAPI document: 3.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param id The unique identifier of the upload
 * @param idStr The unique identifier of the upload in string format
 * @param externalId The external identifier of the upload
 * @param error The error associated with this upload
 * @param status The status of this upload
 * @param activityId The identifier of the activity this upload resulted into
 */

data class Upload (
    /* The unique identifier of the upload */
    @Json(name = "id")
    val id: kotlin.Long? = null,
    /* The unique identifier of the upload in string format */
    @Json(name = "id_str")
    val idStr: kotlin.String? = null,
    /* The external identifier of the upload */
    @Json(name = "external_id")
    val externalId: kotlin.String? = null,
    /* The error associated with this upload */
    @Json(name = "error")
    val error: kotlin.String? = null,
    /* The status of this upload */
    @Json(name = "status")
    val status: kotlin.String? = null,
    /* The identifier of the activity this upload resulted into */
    @Json(name = "activity_id")
    val activityId: kotlin.Long? = null
)

